'use client';

import { useState } from 'react';
import { useLanguage } from '../components/LanguageProvider';
import { applicationYears, caseMetrics, detailedCases, outcomeGroups, yearInsights } from '../lib/site-data';

const filters = [
  ['all', '全部案例', 'All cases'], ['master', '硕士申请', 'Master’s'],
  ['phd', '博士申请', 'Doctoral'], ['complex', '特殊背景', 'Complex profile'],
];

export default function CasesPage() {
  const { lang } = useLanguage();
  const [filter, setFilter] = useState('all');
  const tr = (zh: string, en: string) => lang === 'zh' ? zh : en;
  const visibleCases = detailedCases.filter((item) => filter === 'all' || item.category === filter);
  return <main>
    <section className="inner-hero case-hero"><p>{tr('02 / 案例与数据中心', '02 / CASES & EVIDENCE')}</p><h1>{tr('案例与数据中心', 'Cases & Evidence')}</h1><div><strong>{tr('匿名、分层、可追溯', 'Anonymised, structured, traceable')}</strong><span>{tr('展示背景、难点、策略与结果；不公开姓名、证件、文书或敏感材料。', 'Showing profile, challenge, strategy and outcome—never names, IDs, essays or sensitive documents.')}</span></div></section>
    <section className="case-metrics" id="overview">{caseMetrics.map((metric) => <article key={metric.zh}><strong>{metric.value}</strong><p>{lang === 'zh' ? metric.zh : metric.en}</p></article>)}</section>
    <section className="case-data-block"><div className="case-data-title"><p>2016—2026</p><h2>{tr('年度服务项目量级', 'Estimated annual project volume')}</h2><span>{tr('现有可核验样本为一位核心成员归档的 126 个项目文件夹。考虑团队长期参与规模，页面按约 5 倍系数作保守推算，并以约数展示年度量级；该口径用于说明服务规模，不等同于客户人数、录取数量、成功率或审计数据。', 'The verifiable sample comprises 126 project folders archived by one core team member. To reflect broader team participation over time, annual volume is conservatively estimated at approximately five times the sample. These rounded figures indicate service scale; they are not client counts, admission totals, success rates or audited data.')}</span><a className="method-link" href="/evidence/#methodology">{tr('查看样本、估算方法与使用边界', 'Review the sample, method and limitations')} →</a></div><div className="case-year-table">{applicationYears.map(({ year, count }) => <div key={year}><span>{year}</span><strong>≈{count}</strong><i style={{ width: `${count / 110 * 100}%` }} /></div>)}</div></section>
    <section className="year-insight-section" id="year-analysis"><div className="year-insight-heading"><p>{tr('年度项目分析', 'ANNUAL PROJECT ANALYSIS')}</p><h2>{tr('从年度量级，\n看服务结构的持续扩展。', 'How service scope evolved\nalongside annual volume.')}</h2><span>{tr('年度数字为基于个人归档样本的团队量级估算；业务主题和方法变化来自匿名化文件夹名称与项目结构。页面不公开个人身份、费用或材料内容。', 'Annual figures are team-scale estimates derived from the individual archive sample. Service themes and delivery patterns are drawn from anonymised folder labels and project structure, without disclosing identities, fees or document contents.')}</span></div><div className="year-insight-grid">{yearInsights.map((item) => <article key={item.year}><div><span>{item.year}</span><strong>≈{item.count}</strong><small>{tr('项目量级', 'PROJECT SCALE')}</small></div><h3>{lang === 'zh' ? item.focus.zh : item.focus.en}</h3><p>{lang === 'zh' ? item.analysis.zh : item.analysis.en}</p></article>)}</div></section>
    <section className="case-library-section" id="analysis"><div className="case-library-header"><div><p>{tr('匿名案例分析', 'ANONYMISED CASE ANALYSIS')}</p><h2>{tr('深度匿名案例分析', 'Detailed anonymised case analysis')}</h2></div><div className="case-filters" role="group" aria-label={tr('案例筛选', 'Case filters')}>{filters.map(([value, zh, en]) => <button className={filter === value ? 'active' : ''} type="button" onClick={() => setFilter(value)} key={value}>{tr(zh, en)}</button>)}</div></div><div className="detailed-case-grid">{visibleCases.map((item) => <article key={item.id}><div className="case-card-top"><span>{item.year}</span><small>{lang === 'zh' ? item.categoryLabel.zh : item.categoryLabel.en}</small></div><h3>{lang === 'zh' ? item.title.zh : item.title.en}</h3><div className="case-facts"><span><b>{tr('专业方向', 'DISCIPLINE')}</b>{lang === 'zh' ? item.discipline.zh : item.discipline.en}</span><span><b>{tr('申请层次', 'LEVEL')}</b>{lang === 'zh' ? item.level.zh : item.level.en}</span><span><b>{tr('时间跨度', 'TIMELINE')}</b>{lang === 'zh' ? item.timeline.zh : item.timeline.en}</span><span><b>{tr('服务范围', 'SCOPE')}</b>{lang === 'zh' ? item.serviceScope.zh : item.serviceScope.en}</span></div><dl><div><dt>{tr('背景', 'PROFILE')}</dt><dd>{lang === 'zh' ? item.profile.zh : item.profile.en}</dd></div><div><dt>{tr('核心难点', 'CHALLENGE')}</dt><dd>{lang === 'zh' ? item.challenge.zh : item.challenge.en}</dd></div><div><dt>{tr('策略拆解', 'STRATEGY')}</dt><dd>{lang === 'zh' ? item.strategy.zh : item.strategy.en}</dd></div><div><dt>{tr('证据依据', 'EVIDENCE BASIS')}</dt><dd>{lang === 'zh' ? item.evidenceBasis.zh : item.evidenceBasis.en}</dd></div><div className="result"><dt>{tr('历史结果', 'OUTCOME')}</dt><dd>{lang === 'zh' ? item.result.zh : item.result.en}</dd></div></dl></article>)}</div></section>
    <section className="outcome-section" id="outcomes"><div className="outcome-intro"><p>{tr('结果证据', 'RESULT EVIDENCE')}</p><h2>{tr('历史录取证据覆盖方向', 'Programme areas in archived outcome evidence')}</h2><span>{tr('以下为归档录取结果图片中出现的项目方向，不代表当前合作关系或未来录取承诺。', 'Areas appearing in archived admission-result images; they do not imply current affiliation or future outcomes.')}</span><a className="method-link light" href="/evidence/#outcome-samples">{tr('查看匿名结果样本', 'View anonymised outcome samples')} →</a></div><div className="outcome-groups">{outcomeGroups.map((group, i) => <article key={group.title.zh}><span>0{i + 1}</span><h3>{lang === 'zh' ? group.title.zh : group.title.en}</h3>{group.programmes.map((programme) => <p key={programme.zh}>{lang === 'zh' ? programme.zh : programme.en}<b>↗</b></p>)}</article>)}</div></section>
  </main>;
}
