'use client';
/* eslint-disable @next/next/no-img-element */

import { useLanguage } from '../components/LanguageProvider';
import { assetPath } from '../lib/site-data';
import { ConsultationForm } from '../components/ConsultationForm';

export default function AboutPage() {
  const { lang } = useLanguage();
  const tr = (zh: string, en: string) => lang === 'zh' ? zh : en;
  return <main>
    <section className="inner-hero about-hero"><p>{tr('05 / 关于 AEI', '05 / ABOUT AEI')}</p><h1>{tr('关于 AEI', 'About AEI')}</h1><div><strong>{tr('立足新加坡，连接亚洲与世界', 'Singapore-based, connecting Asia and the world')}</strong><span>{tr('以双语沟通、跨文化理解和项目化执行，服务个人成长与机构合作。', 'Bilingual communication, cross-cultural understanding and disciplined delivery for individuals and institutions.')}</span></div></section>
    <section className="about-profile" id="profile"><div><p>{tr('亚瑟（新加坡）教育学院', 'ASIA EDUCATION INSTITUTION')}</p><h2>{tr('做长期主义的\n教育连接者。', 'A long-term connector\nin education.')}</h2><p>{tr('亚瑟（新加坡）教育学院（AEI）于 2015 年在新加坡成立。业务由早期的硕博申请与学业规划，逐步发展为覆盖学术研究、国际项目、院校合作、职业发展与机构培训的综合教育平台。', 'Asia Education Institution (AEI) was established in Singapore in 2015. Beginning with postgraduate applications and academic planning, it has developed into a broader platform spanning research, global programmes, institutional partnerships, career development and executive learning.')}</p></div><img src={assetPath('learning-room.jpg')} alt={tr('AEI 教育项目', 'AEI education programme')} /></section>
    <section className="about-registry" id="registry"><div><p>{tr('注册与责任主体', 'REGISTRATION & ACCOUNTABILITY')}</p><h2>{tr('谁提供服务，\n由谁承担责任。', 'Who provides the service\nand who is accountable.')}</h2><span>{tr('网站所述 AEI 指向以下新加坡注册主体。正式交易前可使用完整 UEN 在 ACRA Bizfile 核验最新资料。', 'AEI on this website refers to the Singapore-registered entity below. Verify current information in ACRA Bizfile using the full UEN before a formal transaction.')}</span></div><dl><div><dt>{tr('法定名称', 'LEGAL NAME')}</dt><dd>ASIA EDUCATION INSTITUTION PTE. LTD.</dd></div><div><dt>UEN</dt><dd>201510068D</dd></div><div><dt>{tr('注册日期', 'REGISTERED')}</dt><dd>15 April 2015</dd></div><div><dt>{tr('注册地址', 'REGISTERED ADDRESS')}</dt><dd>732 Tampines Street 71, Singapore 520732</dd></div><div><dt>{tr('对外联系', 'CONTACT')}</dt><dd><a href="tel:+6586267896">+65 8626 7896</a><br /><a href="mailto:eric2015aei@gmail.com">eric2015aei@gmail.com</a></dd></div><div><dt>{tr('公开核验', 'PUBLIC VERIFICATION')}</dt><dd><a href="https://www.bizfile.gov.sg/buy-info/search/results" target="_blank" rel="noreferrer">ACRA Bizfile ↗</a></dd></div></dl><small>{tr('公开页面省略具体单元号；注册地址不作为可直接到访的教学园区，咨询与会面须提前预约。', 'The public page omits the precise unit number. The registered address is not presented as a walk-in teaching campus; consultations and meetings are by appointment.')}</small></section>
    <section className="about-timeline"><div><span>2015</span><p>{tr('AEI 在新加坡成立，启动硕士与博士申请服务。', 'AEI established in Singapore; master’s and doctoral application services begin.')}</p></div><div><span>2017</span><p>{tr('扩展学业辅导、职业规划与国际交流业务。', 'Academic support, career planning and international exchange expand.')}</p></div><div><span>2018—19</span><p>{tr('推进课题组互访、研究生论坛与新加坡暑期项目。', 'Research-group visits, postgraduate forums and Singapore summer programmes delivered.')}</p></div><div><span>2020—23</span><p>{tr('发展线上国际课程、创新项目与更广泛的跨学科申请服务。', 'Online international learning, innovation projects and wider interdisciplinary applications develop.')}</p></div><div><span>2024—26</span><p>{tr('形成七条业务线，并扩展全球流动、签证与长期身份规划。', 'Seven connected pathways emerge, including global mobility, visa and long-term status planning.')}</p></div></section>
    <section className="team-section" id="team"><div><p>{tr('项目责任团队', 'ACCOUNTABILITY MODEL')}</p><h2>{tr('每个项目都要知道：\n谁负责、谁审核、谁确认。', 'Every project should identify\nwho owns, reviews and approves.')}</h2><span>{tr('AEI 采用项目责任制。为保护客户与顾问隐私，公开页面重点说明责任机制；具体项目负责人、专业顾问与审核安排将在服务确认阶段明确。', 'AEI operates with defined project accountability. To protect client and adviser privacy, the public site explains the responsibility structure; the project owner, specialist advisers and review arrangements are confirmed at engagement stage.')}</span></div><div>{[[tr('项目负责人', 'Project Owner'), tr('作为单一联络人，确认目标、范围、节点、责任与变更。', 'Acts as the single point of contact for objectives, scope, milestones, ownership and change.')],[tr('专业顾问', 'Domain Advisor'), tr('按申请、研究、课程或机构主题提供专业判断与反馈。', 'Provides domain judgement and feedback for admissions, research, curriculum or institutional themes.')],[tr('质量与隐私审核', 'Quality & Privacy Review'), tr('核对事实、版本、截止日期、公开边界和个人信息处理。', 'Checks facts, versions, deadlines, publication boundaries and personal-data handling.')]].map(([title, body], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="team-network" id="network"><div><p>{tr('跨国项目协作网络', 'CROSS-BORDER PROJECT NETWORK')}</p><h2>{tr('服务靠团队协作，\n公开信息以事实核验为准。', 'Team-based delivery,\nwith public profiles verified before publication.')}</h2><span>{tr('项目可按需要配置中国家庭沟通、升学、课程、竞赛、研究、出版、国际项目与全球流动等工作模块。以下公开名单仅确认姓名属于机构提供的协作网络；个人学历、现任职务、专业资质与具体项目经历将在本人授权和事实核验后补充。具体参与人员以项目确认书为准。', 'Projects may combine China-family communication, admissions, curriculum, competitions, research, publishing, global programmes and mobility. The names below are presented only as an organisation-provided collaboration roster. Education, current roles, professional credentials and project histories will be added only after consent and factual verification. Actual participation is confirmed in each engagement.')}</span></div><div className="team-name-grid">{['Eric', 'Bibo', 'Lily', 'Valerin', 'Amanda', 'Rae', 'Fiona', 'Peter', 'Vincent Dai', 'YZ'].map((name, i) => <article key={name}><span>{String(i + 1).padStart(2, '0')}</span><strong>{name}</strong><small>{tr('项目协作网络', 'PROJECT COLLABORATION NETWORK')}</small></article>)}</div></section>
    <section className="principle-section" id="principles"><div><p>{tr('我们的原则', 'OUR PRINCIPLES')}</p><h2>{tr('专业来自清晰，\n信任来自负责。', 'Clarity builds professionalism.\nAccountability builds trust.')}</h2></div><div>{[[tr('真实', 'Authentic'), tr('只使用真实背景、真实材料与可核实证据。', 'Authentic profiles, materials and verifiable evidence only.')],[tr('清晰', 'Clear'), tr('先定义目标、范围与责任，再开始执行。', 'Define goals, scope and responsibilities before delivery.')],[tr('匿名', 'Private'), tr('案例公开时移除姓名、证件和敏感材料。', 'Public cases remove names, IDs and sensitive documents.')],[tr('不承诺结果', 'No guarantees'), tr('历史结果不构成未来录取、签证、就业或发表承诺。', 'Past outcomes do not guarantee admission, visa, employment or publication.')]].map(([title, body], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="contact-panel" id="contact"><p>{tr('联系 AEI', 'CONTACT AEI')}</p><h2>{tr('从一次有目标的对话开始。', 'Start with a purposeful conversation.')}</h2><div><a href="tel:+6586267896"><small>{tr('电话', 'PHONE')}</small><strong>+65 8626 7896</strong></a><a href="mailto:eric2015aei@gmail.com"><small>{tr('电子邮件', 'EMAIL')}</small><strong>eric2015aei@gmail.com</strong></a><a href="https://www.instagram.com/asiaeducationinstitution/" target="_blank" rel="noreferrer"><small>{tr('社交媒体', 'INSTAGRAM')}</small><strong>@asiaeducationinstitution</strong></a></div><span>{tr('新加坡 · 预约沟通', 'Singapore · By appointment')}</span></section>
    <section className="consultation-section" id="consultation"><div><p>{tr('预约咨询', 'CONSULTATION')}</p><h2>{tr('学生与机构，\n走不同的咨询路径。', 'Separate enquiry paths\nfor individuals and institutions.')}</h2><span>{tr('请先提交目标和时间信息。不要在首次咨询中发送身份证件、成绩单、合同或其他敏感文件。', 'Start with goals and timing. Do not send identity documents, transcripts, contracts or other sensitive files in the first enquiry.')}</span></div><ConsultationForm /></section>
  </main>;
}
