'use client';
/* eslint-disable @next/next/no-img-element */

import { useLanguage } from '../components/LanguageProvider';
import { assetPath } from '../lib/site-data';

export default function EvidencePage() {
  const { lang } = useLanguage();
  const tr = (zh: string, en: string) => lang === 'zh' ? zh : en;
  const samples = [
    ['evidence-hku-business-analytics.png', tr('香港大学商业分析硕士历史录取结果样本', 'Archived HKU Business Analytics result sample')],
    ['evidence-hku-accounting.jpeg', tr('香港大学会计学硕士历史录取结果样本', 'Archived HKU Accounting result sample')],
    ['evidence-hkbu-management.jpeg', tr('香港浸会大学管理学相关历史录取结果样本', 'Archived HKBU management-related result sample')],
  ];
  return <main>
    <section className="inner-hero evidence-hero"><p>{tr('06 / 证据与透明度中心', '06 / EVIDENCE & TRANSPARENCY')}</p><h1>{tr('证据与透明度', 'Evidence & Transparency')}</h1><div><strong>{tr('以可核验样本为基础，清楚区分事实、估算与历史成果', 'A verifiable basis, with facts, estimates and historical outcomes clearly distinguished')}</strong><span>{tr('登记信息、可核验样本、估算口径、匿名证据与外部记录分别呈现，在透明与隐私之间保持清晰边界。', 'Registration, verifiable samples, estimation methods, anonymised evidence and public records are presented separately, balancing transparency with privacy.')}</span></div></section>
    <section className="registry-section" id="registry"><div><p>{tr('公司登记', 'ENTITY REGISTRATION')}</p><h2>{tr('新加坡注册主体', 'Singapore-registered entity')}</h2><span>{tr('以下为公开登记资料摘要。需要正式交易前，可使用完整 UEN 在 ACRA Bizfile 核验最新状态。', 'The following summarises public registry information. Before a formal transaction, use the full UEN in ACRA Bizfile to verify the latest status.')}</span></div><dl><div><dt>{tr('法定名称', 'LEGAL NAME')}</dt><dd>ASIA EDUCATION INSTITUTION PTE. LTD.</dd></div><div><dt>UEN</dt><dd>201510068D</dd></div><div><dt>{tr('注册日期', 'REGISTERED')}</dt><dd>15 April 2015</dd></div><div><dt>{tr('公开状态', 'PUBLIC STATUS')}</dt><dd>{tr('存续 / Live', 'Live')}</dd></div><div><dt>{tr('注册地址', 'REGISTERED ADDRESS')}</dt><dd>Tampines Courtview, 732 Tampines Street 71, Singapore 520732</dd></div><div><dt>{tr('核验入口', 'VERIFY')}</dt><dd><a href="https://www.bizfile.gov.sg/buy-info/search/results" target="_blank" rel="noreferrer">ACRA Bizfile ↗</a></dd></div></dl><small>{tr('公开页面省略具体单元号。该地址为公司注册地址；咨询与会面须提前预约，不作为可直接到访的教学园区。', 'The public page omits the precise unit number. This is the registered company address; consultations and meetings are by appointment, and it is not presented as a walk-in teaching campus.')}</small></section>
    <section className="methodology-section" id="methodology"><div><p>{tr('统计方法', 'METHODOLOGY')}</p><h2>{tr('三组数字，\n分别基于什么口径？', 'How the sample, multiplier and\npublic figures are defined')}</h2></div><div className="methodology-grid"><article><strong>126 / 55</strong><h3>{tr('个人归档样本', 'Verified personal archive sample')}</h3><p>{tr('截至 2026 年 8 月 31 日，一名核心成员的归档包含 126 个一级项目文件夹及 55 张可识别的历史结果图片。企业介绍、行政资料与汇总文件不计入。该组数字是可追溯的样本事实。', 'As at 31 August 2026, one core team member’s archive contained 126 first-level project folders and 55 identifiable historical outcome images. Corporate profiles, administrative material and summary folders are excluded. These figures form the traceable sample basis.')}</p></article><article><strong>×5</strong><h3>{tr('团队量级系数', 'Team-scale multiplier')}</h3><p>{tr('现有可核验归档仅反映一名核心成员的工作量。结合团队长期参与情况，网站采用约 5 倍系数保守估算整体服务量级；该系数用于规模表达，不是逐项目审计结果。', 'The verified archive reflects the workload of one core team member. Based on long-term team participation, the site applies an approximate five-times multiplier as a conservative indication of overall scale; it is not a project-by-project audit.')}</p></article><article><strong>600+ / 275+</strong><h3>{tr('公开展示量级', 'Public scale indicators')}</h3><p>{tr('分别表示团队累计服务项目与历史结果记录的保守约数。它们不等同于独立客户数、录取总数、成功率、财务数据或经审计统计。', 'These are rounded, conservative indicators of cumulative team projects and historical outcome records. They are not unique-client counts, admission totals, success rates, financial data or audited statistics.')}</p></article></div><p className="method-note">{tr('样本覆盖 2016—2026 年连续 11 个归档年度，主体为成功完成或形成明确结果的项目，另有少量在办、关闭或单项交付。原始清单因隐私不公开；如确有核验需要，可在适当保密安排下进行匿名化审阅。', 'The sample covers 11 consecutive archive years from 2016 to 2026. Most projects were completed successfully or reached a documented outcome, with a small number in progress, closed or limited to one deliverable. The raw list remains private, but an anonymised review may be arranged where verification is appropriate and confidentiality is protected.')}</p></section>
    <section className="evidence-samples" id="outcome-samples"><div className="detail-section-heading"><p>{tr('匿名结果样本', 'ANONYMISED OUTCOME SAMPLES')}</p><h2>{tr('以匿名证据呈现真实历史结果。', 'Anonymised evidence of historical outcomes.')}</h2><span>{tr('以下仅展示已检查并完成身份遮挡的历史样本。院校标识属于相应院校，仅用于识别历史结果，不代表当前合作或背书。', 'Only inspected samples with identity fields obscured are shown. Institutional marks belong to their respective institutions and identify historical outcomes only; they do not imply current partnership or endorsement.')}</span></div><div>{samples.map(([src, caption]) => <figure key={src}><a href={assetPath(src)} target="_blank" rel="noreferrer"><img src={assetPath(src)} alt={caption} /></a><figcaption>{caption}</figcaption></figure>)}</div></section>
    <section className="external-traces" id="external-traces"><div><p>{tr('外部公开记录', 'EXTERNAL PUBLIC TRACES')}</p><h2>{tr('以公开记录补充机构信息。', 'Public records provide an independent reference.')}</h2></div><div><a href="https://www.acra.gov.sg/resources/guides-forms/using-bizfiles-search-functions/" target="_blank" rel="noreferrer"><span>01</span><strong>{tr('ACRA：如何使用 Bizfile 核验实体', 'ACRA: how to verify an entity in Bizfile')}</strong><b>↗</b></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10150614/" target="_blank" rel="noreferrer"><span>02</span><strong>{tr('公开研究记录：AEI 资助项目 AEI-001', 'Public research record: AEI-funded project AEI-001')}</strong><b>↗</b></a><a href="https://mp.weixin.qq.com/s/d9Yn5M2t9GhCYt4tp42w3Q" target="_blank" rel="noreferrer"><span>03</span><strong>{tr('2019 研究生国际学术论坛历史记录', '2019 postgraduate academic forum record')}</strong><b>↗</b></a><a href="https://mp.weixin.qq.com/s/VsTsCpU0qRYJHzmKRKVtOw" target="_blank" rel="noreferrer"><span>04</span><strong>{tr('2019 新加坡暑期项目历史记录', '2019 Singapore summer programme record')}</strong><b>↗</b></a></div></section>
  </main>;
}
