'use client';
/* eslint-disable @next/next/no-img-element */

import { useLanguage } from '../components/LanguageProvider';
import { assetPath } from '../lib/site-data';

export default function EvidencePage() {
  const { lang } = useLanguage();
  const tr = (zh: string, en: string) => lang === 'zh' ? zh : en;
  const samples = [
    ['evidence-hku-business-analytics.png', tr('香港大学商业分析硕士历史录取结果样本', 'Archived HKU Business Analytics result sample')],
    ['evidence-hku-accounting.jpeg', tr('香港大学会计学硕士历史录取结果样本', 'Archived HKU Accounting result sample')],
    ['evidence-hkbu-management.jpeg', tr('香港浸会大学管理学相关历史录取结果样本', 'Archived HKBU management-related result sample')],
  ];
  return <main>
    <section className="inner-hero evidence-hero"><p>{tr('06 / 证据与透明度中心', '06 / EVIDENCE & TRANSPARENCY')}</p><h1>{tr('证据与透明度', 'Evidence & Transparency')}</h1><div><strong>{tr('把“我们是谁”和“数字从哪里来”分开说清楚', 'Clarifying who we are and where the numbers come from')}</strong><span>{tr('登记信息、统计口径、匿名证据与外部记录分别呈现；可验证不等于公开个人隐私。', 'Registration, methodology, anonymised evidence and external traces are presented separately; verifiability does not require publishing personal data.')}</span></div></section>
    <section className="registry-section" id="registry"><div><p>{tr('公司登记', 'ENTITY REGISTRATION')}</p><h2>{tr('新加坡注册主体', 'Singapore-registered entity')}</h2><span>{tr('以下为公开登记资料摘要。需要正式交易前，可使用 UEN 在 ACRA Bizfile 核验最新状态。', 'The following summarises public registry information. Before a formal transaction, use the UEN in ACRA Bizfile to verify the latest status.')}</span></div><dl><div><dt>{tr('法定名称', 'LEGAL NAME')}</dt><dd>ASIA EDUCATION INSTITUTION PTE. LTD.</dd></div><div><dt>UEN</dt><dd>201510068D</dd></div><div><dt>{tr('注册日期', 'REGISTERED')}</dt><dd>15 April 2015</dd></div><div><dt>{tr('公开状态', 'PUBLIC STATUS')}</dt><dd>{tr('存续 / Live', 'Live')}</dd></div><div><dt>{tr('注册地址', 'REGISTERED ADDRESS')}</dt><dd>732 Tampines Street 71, #02-111, Tampines Courtview, Singapore 520732</dd></div><div><dt>{tr('核验入口', 'VERIFY')}</dt><dd><a href="https://www.bizfile.gov.sg/buy-info/search/results" target="_blank" rel="noreferrer">ACRA Bizfile ↗</a></dd></div></dl><small>{tr('该地址为公司注册地址；咨询与会面须提前预约，不作为可直接到访的教学园区。', 'This is the registered company address. Consultations and meetings are by appointment; it is not presented as a walk-in teaching campus.')}</small></section>
    <section className="methodology-section" id="methodology"><div><p>{tr('统计方法', 'METHODOLOGY')}</p><h2>{tr('126、11 与 55，\n分别代表什么？', 'What do 126, 11 and 55\nactually mean?')}</h2></div><div className="methodology-grid"><article><strong>126</strong><h3>{tr('项目文件夹', 'Project folders')}</h3><p>{tr('截至 2026 年 8 月 31 日，对 2016—2026 年申请与服务归档中的一级文件夹进行快照统计；企业介绍、AEI 行政资料和汇总文件夹不计入。一个文件夹基本对应一个项目。', 'Snapshot on 31 August 2026 of first-level folders in the 2016–2026 application and service archive. Corporate profiles, AEI administration and summary folders are excluded. One folder generally represents one project.')}</p></article><article><strong>11</strong><h3>{tr('连续归档年度', 'Archive years')}</h3><p>{tr('从 2016 至 2026 的连续年度项目记录。数字描述归档跨度，不等同于持续经营承诺或每年相同服务量。', 'Continuous annual project records from 2016 to 2026. This describes archive coverage, not a promise of identical annual volume.')}</p></article><article><strong>55</strong><h3>{tr('结果证据图片', 'Evidence images')}</h3><p>{tr('归档中可识别的历史录取结果图片数量。它不是 55 名学生，也不是 55 个独立录取，更不是成功率。', 'The number of identifiable archived admission-result images. It does not mean 55 students, 55 independent offers or a success rate.')}</p></article></div><p className="method-note">{tr('档案主体为成功完成或形成明确结果的项目；另有少量在办、关闭或单项交付。原始清单因隐私不公开，可在合适的保密安排下进行匿名化核验。', 'Most archived projects were successfully completed or reached a documented outcome; a small number remain in progress, closed or limited to one deliverable. The raw list is private but can be reviewed in anonymised form under an appropriate confidentiality arrangement.')}</p></section>
    <section className="evidence-samples" id="outcome-samples"><div className="detail-section-heading"><p>{tr('匿名结果样本', 'ANONYMISED OUTCOME SAMPLES')}</p><h2>{tr('看得到证据，也守得住隐私。', 'Evidence visible. Privacy protected.')}</h2><span>{tr('以下仅展示已检查并完成身份遮挡的历史样本。院校标识属于相应院校，仅用于识别历史结果，不代表当前合作或背书。', 'Only inspected samples with identity fields obscured are shown. Institutional marks belong to their respective institutions and identify historical outcomes only; they do not imply current partnership or endorsement.')}</span></div><div>{samples.map(([src, caption]) => <figure key={src}><a href={assetPath(src)} target="_blank" rel="noreferrer"><img src={assetPath(src)} alt={caption} /></a><figcaption>{caption}</figcaption></figure>)}</div></section>
    <section className="external-traces" id="external-traces"><div><p>{tr('外部公开记录', 'EXTERNAL PUBLIC TRACES')}</p><h2>{tr('将自述与外部记录分开。', 'Separating self-description from public records.')}</h2></div><div><a href="https://www.acra.gov.sg/resources/guides-forms/using-bizfiles-search-functions/" target="_blank" rel="noreferrer"><span>01</span><strong>{tr('ACRA：如何使用 Bizfile 核验实体', 'ACRA: how to verify an entity in Bizfile')}</strong><b>↗</b></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10150614/" target="_blank" rel="noreferrer"><span>02</span><strong>{tr('公开研究记录：AEI 资助项目 AEI-001', 'Public research record: AEI-funded project AEI-001')}</strong><b>↗</b></a><a href="https://mp.weixin.qq.com/s/d9Yn5M2t9GhCYt4tp42w3Q" target="_blank" rel="noreferrer"><span>03</span><strong>{tr('2019 研究生国际学术论坛历史记录', '2019 postgraduate academic forum record')}</strong><b>↗</b></a><a href="https://mp.weixin.qq.com/s/VsTsCpU0qRYJHzmKRKVtOw" target="_blank" rel="noreferrer"><span>04</span><strong>{tr('2019 新加坡暑期项目历史记录', '2019 Singapore summer programme record')}</strong><b>↗</b></a></div></section>
  </main>;
}
